### ISSUE TITLE
[PE-D] There are a lot of fields to add.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-2/tp#160]
There are a lot of fields to add just to add a person to the addressbook. All fields except tags are compulsory. Perhaps it might not be necessary to include all fields (Making some fields optional such as address). It might not be necessary to know the address of the student right? Perhaps applicable to tutor as the address can be the location of the tutorial.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: xiangjunn/ped#17

**Comment by chengseong** [comment]
Suggestion noted
